
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: awio

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: growfund_development
test:
  <<: *default
  database: growfund_test
production:
  primary: &primary_production
    <<: *default
    database: growfund_production
    username: growfund
    password: <%= ENV["GROWFUND_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: growfund_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: growfund_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: growfund_production_cable
    migrations_paths: db/cable_migrate
